services:
  neutrino:
    container_name: neutrino
    build:
      context: ../..
      dockerfile: apps/neutrino/Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        CLAUDE_API_KEY: ${CLAUDE_API_KEY}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        RABBITMQ_CONN_URL: ${RABBITMQ_CONN_URL}
    ports:
      - "3030:3030"
    env_file:
      - apps/neutrino/.env
